### ISSUE TITLE
Support File URIs

### ISSUE THREAD

**Issue by pdalpra** [NET-A-PORTER/scala-uri#70]
Hi,

I'm trying to use scala-uri in Gatling, to replace a "quick-and-dirty" hack on URIs to support spaces in filenames.
But I'm unfortunately unable to construct valid file URIs, as scala-uri always add a leading-slash, thinking the URI is relative :

``` scala
scala> import java.io.File, java.net.URI, com.netaporter.uri._, com.netaporter.uri.dsl._
import java.io.File
import java.net.URI
import com.netaporter.uri._
import com.netaporter.uri.dsl._

scala> new File(sys.props("user.home"))
res0: java.io.File = /Users/pdalpra

scala> res0.toURI
res1: java.net.URI = file:/Users/pdalpra/

scala> Uri(res1)
res2: com.netaporter.uri.Uri = /file:/Users/pdalpra/
```

Would it be possible to support file URIs ?

**Comment by theon** [comment]
@pdalpra Sorry for not getting back to you on this

I don't think including localhost has any impact on how scala-uri behaves. The reason you are seeing different behaviour, is just that in your first comment you have a single slash after the file scheme (`file:/Users/pdalpra/`) and in the second example you have a double slash (`file://localhost`).

Looking at the [RFC 1738](http://tools.ietf.org/html/rfc1738), I believe two slashes is correct and scala-uri is doing the right thing.

Let me know if you think otherwise!
